"""Add validation fields to FileUpload

Revision ID: 878efd0e2f11
Revises: 
Create Date: 2025-08-26 16:20:18.663656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878efd0e2f11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('validation_status', sa.String(length=50), nullable=True))
    op.add_column('file_uploads', sa.Column('validation_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_uploads', 'validation_error')
    op.drop_column('file_uploads', 'validation_status')
    # ### end Alembic commands ###
